// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chainloop-dev/chainloop/app/controlplane/pkg/data/ent/group"
	"github.com/chainloop-dev/chainloop/app/controlplane/pkg/data/ent/groupuser"
	"github.com/chainloop-dev/chainloop/app/controlplane/pkg/data/ent/predicate"
	"github.com/chainloop-dev/chainloop/app/controlplane/pkg/data/ent/user"
	"github.com/google/uuid"
)

// GroupUserUpdate is the builder for updating GroupUser entities.
type GroupUserUpdate struct {
	config
	hooks     []Hook
	mutation  *GroupUserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GroupUserUpdate builder.
func (guu *GroupUserUpdate) Where(ps ...predicate.GroupUser) *GroupUserUpdate {
	guu.mutation.Where(ps...)
	return guu
}

// SetGroupID sets the "group_id" field.
func (guu *GroupUserUpdate) SetGroupID(u uuid.UUID) *GroupUserUpdate {
	guu.mutation.SetGroupID(u)
	return guu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (guu *GroupUserUpdate) SetNillableGroupID(u *uuid.UUID) *GroupUserUpdate {
	if u != nil {
		guu.SetGroupID(*u)
	}
	return guu
}

// SetUserID sets the "user_id" field.
func (guu *GroupUserUpdate) SetUserID(u uuid.UUID) *GroupUserUpdate {
	guu.mutation.SetUserID(u)
	return guu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (guu *GroupUserUpdate) SetNillableUserID(u *uuid.UUID) *GroupUserUpdate {
	if u != nil {
		guu.SetUserID(*u)
	}
	return guu
}

// SetMaintainer sets the "maintainer" field.
func (guu *GroupUserUpdate) SetMaintainer(b bool) *GroupUserUpdate {
	guu.mutation.SetMaintainer(b)
	return guu
}

// SetNillableMaintainer sets the "maintainer" field if the given value is not nil.
func (guu *GroupUserUpdate) SetNillableMaintainer(b *bool) *GroupUserUpdate {
	if b != nil {
		guu.SetMaintainer(*b)
	}
	return guu
}

// SetUpdatedAt sets the "updated_at" field.
func (guu *GroupUserUpdate) SetUpdatedAt(t time.Time) *GroupUserUpdate {
	guu.mutation.SetUpdatedAt(t)
	return guu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (guu *GroupUserUpdate) SetNillableUpdatedAt(t *time.Time) *GroupUserUpdate {
	if t != nil {
		guu.SetUpdatedAt(*t)
	}
	return guu
}

// SetDeletedAt sets the "deleted_at" field.
func (guu *GroupUserUpdate) SetDeletedAt(t time.Time) *GroupUserUpdate {
	guu.mutation.SetDeletedAt(t)
	return guu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (guu *GroupUserUpdate) SetNillableDeletedAt(t *time.Time) *GroupUserUpdate {
	if t != nil {
		guu.SetDeletedAt(*t)
	}
	return guu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (guu *GroupUserUpdate) ClearDeletedAt() *GroupUserUpdate {
	guu.mutation.ClearDeletedAt()
	return guu
}

// SetGroup sets the "group" edge to the Group entity.
func (guu *GroupUserUpdate) SetGroup(g *Group) *GroupUserUpdate {
	return guu.SetGroupID(g.ID)
}

// SetUser sets the "user" edge to the User entity.
func (guu *GroupUserUpdate) SetUser(u *User) *GroupUserUpdate {
	return guu.SetUserID(u.ID)
}

// Mutation returns the GroupUserMutation object of the builder.
func (guu *GroupUserUpdate) Mutation() *GroupUserMutation {
	return guu.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (guu *GroupUserUpdate) ClearGroup() *GroupUserUpdate {
	guu.mutation.ClearGroup()
	return guu
}

// ClearUser clears the "user" edge to the User entity.
func (guu *GroupUserUpdate) ClearUser() *GroupUserUpdate {
	guu.mutation.ClearUser()
	return guu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (guu *GroupUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, guu.sqlSave, guu.mutation, guu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guu *GroupUserUpdate) SaveX(ctx context.Context) int {
	affected, err := guu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (guu *GroupUserUpdate) Exec(ctx context.Context) error {
	_, err := guu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guu *GroupUserUpdate) ExecX(ctx context.Context) {
	if err := guu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guu *GroupUserUpdate) check() error {
	if guu.mutation.GroupCleared() && len(guu.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUser.group"`)
	}
	if guu.mutation.UserCleared() && len(guu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUser.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (guu *GroupUserUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GroupUserUpdate {
	guu.modifiers = append(guu.modifiers, modifiers...)
	return guu
}

func (guu *GroupUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := guu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupuser.Table, groupuser.Columns, sqlgraph.NewFieldSpec(groupuser.FieldGroupID, field.TypeUUID), sqlgraph.NewFieldSpec(groupuser.FieldUserID, field.TypeUUID))
	if ps := guu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guu.mutation.Maintainer(); ok {
		_spec.SetField(groupuser.FieldMaintainer, field.TypeBool, value)
	}
	if value, ok := guu.mutation.UpdatedAt(); ok {
		_spec.SetField(groupuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := guu.mutation.DeletedAt(); ok {
		_spec.SetField(groupuser.FieldDeletedAt, field.TypeTime, value)
	}
	if guu.mutation.DeletedAtCleared() {
		_spec.ClearField(groupuser.FieldDeletedAt, field.TypeTime)
	}
	if guu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.GroupTable,
			Columns: []string{groupuser.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.GroupTable,
			Columns: []string{groupuser.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if guu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.UserTable,
			Columns: []string{groupuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.UserTable,
			Columns: []string{groupuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(guu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, guu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	guu.mutation.done = true
	return n, nil
}

// GroupUserUpdateOne is the builder for updating a single GroupUser entity.
type GroupUserUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GroupUserMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetGroupID sets the "group_id" field.
func (guuo *GroupUserUpdateOne) SetGroupID(u uuid.UUID) *GroupUserUpdateOne {
	guuo.mutation.SetGroupID(u)
	return guuo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (guuo *GroupUserUpdateOne) SetNillableGroupID(u *uuid.UUID) *GroupUserUpdateOne {
	if u != nil {
		guuo.SetGroupID(*u)
	}
	return guuo
}

// SetUserID sets the "user_id" field.
func (guuo *GroupUserUpdateOne) SetUserID(u uuid.UUID) *GroupUserUpdateOne {
	guuo.mutation.SetUserID(u)
	return guuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (guuo *GroupUserUpdateOne) SetNillableUserID(u *uuid.UUID) *GroupUserUpdateOne {
	if u != nil {
		guuo.SetUserID(*u)
	}
	return guuo
}

// SetMaintainer sets the "maintainer" field.
func (guuo *GroupUserUpdateOne) SetMaintainer(b bool) *GroupUserUpdateOne {
	guuo.mutation.SetMaintainer(b)
	return guuo
}

// SetNillableMaintainer sets the "maintainer" field if the given value is not nil.
func (guuo *GroupUserUpdateOne) SetNillableMaintainer(b *bool) *GroupUserUpdateOne {
	if b != nil {
		guuo.SetMaintainer(*b)
	}
	return guuo
}

// SetUpdatedAt sets the "updated_at" field.
func (guuo *GroupUserUpdateOne) SetUpdatedAt(t time.Time) *GroupUserUpdateOne {
	guuo.mutation.SetUpdatedAt(t)
	return guuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (guuo *GroupUserUpdateOne) SetNillableUpdatedAt(t *time.Time) *GroupUserUpdateOne {
	if t != nil {
		guuo.SetUpdatedAt(*t)
	}
	return guuo
}

// SetDeletedAt sets the "deleted_at" field.
func (guuo *GroupUserUpdateOne) SetDeletedAt(t time.Time) *GroupUserUpdateOne {
	guuo.mutation.SetDeletedAt(t)
	return guuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (guuo *GroupUserUpdateOne) SetNillableDeletedAt(t *time.Time) *GroupUserUpdateOne {
	if t != nil {
		guuo.SetDeletedAt(*t)
	}
	return guuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (guuo *GroupUserUpdateOne) ClearDeletedAt() *GroupUserUpdateOne {
	guuo.mutation.ClearDeletedAt()
	return guuo
}

// SetGroup sets the "group" edge to the Group entity.
func (guuo *GroupUserUpdateOne) SetGroup(g *Group) *GroupUserUpdateOne {
	return guuo.SetGroupID(g.ID)
}

// SetUser sets the "user" edge to the User entity.
func (guuo *GroupUserUpdateOne) SetUser(u *User) *GroupUserUpdateOne {
	return guuo.SetUserID(u.ID)
}

// Mutation returns the GroupUserMutation object of the builder.
func (guuo *GroupUserUpdateOne) Mutation() *GroupUserMutation {
	return guuo.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (guuo *GroupUserUpdateOne) ClearGroup() *GroupUserUpdateOne {
	guuo.mutation.ClearGroup()
	return guuo
}

// ClearUser clears the "user" edge to the User entity.
func (guuo *GroupUserUpdateOne) ClearUser() *GroupUserUpdateOne {
	guuo.mutation.ClearUser()
	return guuo
}

// Where appends a list predicates to the GroupUserUpdate builder.
func (guuo *GroupUserUpdateOne) Where(ps ...predicate.GroupUser) *GroupUserUpdateOne {
	guuo.mutation.Where(ps...)
	return guuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guuo *GroupUserUpdateOne) Select(field string, fields ...string) *GroupUserUpdateOne {
	guuo.fields = append([]string{field}, fields...)
	return guuo
}

// Save executes the query and returns the updated GroupUser entity.
func (guuo *GroupUserUpdateOne) Save(ctx context.Context) (*GroupUser, error) {
	return withHooks(ctx, guuo.sqlSave, guuo.mutation, guuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guuo *GroupUserUpdateOne) SaveX(ctx context.Context) *GroupUser {
	node, err := guuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guuo *GroupUserUpdateOne) Exec(ctx context.Context) error {
	_, err := guuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guuo *GroupUserUpdateOne) ExecX(ctx context.Context) {
	if err := guuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guuo *GroupUserUpdateOne) check() error {
	if guuo.mutation.GroupCleared() && len(guuo.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUser.group"`)
	}
	if guuo.mutation.UserCleared() && len(guuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupUser.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (guuo *GroupUserUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GroupUserUpdateOne {
	guuo.modifiers = append(guuo.modifiers, modifiers...)
	return guuo
}

func (guuo *GroupUserUpdateOne) sqlSave(ctx context.Context) (_node *GroupUser, err error) {
	if err := guuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupuser.Table, groupuser.Columns, sqlgraph.NewFieldSpec(groupuser.FieldGroupID, field.TypeUUID), sqlgraph.NewFieldSpec(groupuser.FieldUserID, field.TypeUUID))
	if id, ok := guuo.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "GroupUser.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := guuo.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "GroupUser.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := guuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !groupuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := guuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guuo.mutation.Maintainer(); ok {
		_spec.SetField(groupuser.FieldMaintainer, field.TypeBool, value)
	}
	if value, ok := guuo.mutation.UpdatedAt(); ok {
		_spec.SetField(groupuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := guuo.mutation.DeletedAt(); ok {
		_spec.SetField(groupuser.FieldDeletedAt, field.TypeTime, value)
	}
	if guuo.mutation.DeletedAtCleared() {
		_spec.ClearField(groupuser.FieldDeletedAt, field.TypeTime)
	}
	if guuo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.GroupTable,
			Columns: []string{groupuser.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guuo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.GroupTable,
			Columns: []string{groupuser.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if guuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.UserTable,
			Columns: []string{groupuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupuser.UserTable,
			Columns: []string{groupuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(guuo.modifiers...)
	_node = &GroupUser{config: guuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guuo.mutation.done = true
	return _node, nil
}
